---
- hosts: all
  gather_facts: false
  vars:
    ansible_ssh_private_key: "/home/rmendes/.ssh/quicklab.key"
  tasks:

    - name: Install Packages
      become: yes
      yum:
        name: "{{ package }}"
        state: present

